default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: math_problem_finder_development

test:
  <<: *default
  database: math_problem_finder_test

production:
  <<: *default
  database: math_problem_finder_production
  username: math_problem_finder
  password: <%= ENV['MATH_PROBLEM_FINDER_DATABASE_PASSWORD'] %>
